### ISSUE TITLE
Error Communicating with Remote Browser

### ISSUE THREAD

**Issue by gurvinderd** [SeleniumHQ/www.seleniumhq.org#70]
I can see this issue has been reported earlier but didn't find any concrete solution.
Can someone help, Thanks.

`org.openqa.selenium.WebDriverException: Error communicating with the remote browser. It may have died.
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'hub', ip: '*', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-573.8.1.el6.x86_64', java.version: '1.8.0_45-internal'
Driver info: driver.version: EventFiringWebDriver
Command duration or timeout: 421 milliseconds
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: '*', ip: '*', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-573.8.1.el6.x86_64', java.version: '1.7.0_76'
*** Element info: {Using=css selector, value=.btn-action.tif-new}
Session ID: de133790-7d12-4d98-83da-5a5bd7191138
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{platform=LINUX, javascriptEnabled=true, acceptSslCerts=true, browserName=firefox, rotatable=false, locationContextEnabled=true, webdriver.remote.sessionid=de133790-7d12-4d98-83da-5a5bd7191138, version=42.0, cssSelectorsEnabled=true, databaseEnabled=true, handlesAlerts=true, webStorageEnabled=true, nativeEvents=false, applicationCacheEnabled=true, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:605)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:358)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByCssSelector(RemoteWebDriver.java:447)
	at org.openqa.selenium.By$ByCssSelector.findElement(By.java:426)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:350)
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy17.click(Unknown Source)
	at com.*.BaseElement.click(BaseElement.java:71)
	at com.*.WaitEnabledBaseElement.click(WaitEnabledBaseElement.java:34)
	*****
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
System info: host: 'hub', ip: '*', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-573.8.1.el6.x86_64', java.version: '1.8.0_45-internal'
Driver info: driver.version: EventFiringWebDriver
Build info: version: '2.46.0', revision: '61506a4624b13675f24581e453592342b7485d71', time: '2015-06-04 10:22:50'
System info: host: '*', ip: '*', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-573.8.1.el6.x86_64', java.version: '1.7.0_76'
Driver info: driver.version: unknown`

**Comment by gurvinderd** [comment]
Dup : https://github.com/SeleniumHQ/selenium/issues/1810
